Create d9.module.languagefield.droplist.language.by.continent
drupalportugal/snippets pull request #1
Opened 2021-03-07 11:11 UTC by adaragaopt

Módulo Language Field - Lista de países por continentes

O módulo aceita apenas códigos ISO 639-1 em minúsculas, mas como não encontrei esta informação em lado nenhum e tive de a compilar usando informação dispersa, incluí muitos códigos ISO 639-2 e ISO 639-3, nos idiomas não incluídos na ISO 639-1. Estes são ignorados pelo módulo, mas caso venham a ser suportados os novos idiomas devem aparecer.

2021-03-07 12:25 UTC, ricardoamaro reviewed
Obrigado. Agora o ideal é colocares numa pasta junto com um README.md a descrever o que faz

2021-03-07 17:18 UTC, adaragaopt commented
Criada a pasta e o README.md.

Talvez não seja má ideia criar algumas regras para não ficar tudo muito confuso.
Como o que partilhei é referente a um módulo, criei a pasta referindo que é um módulo e o nome do modulo (machine name).
E no nome do ficheiro comecei com "d9", para referir a versão em que testei isto.

Não sei se esta será a melhor forma, ou se alguma forma padronizada de fazer isto.

Alguém com mais experiência nisto possa ajudar ?

2021-03-07 18:17 UTC, ricardoamaro approved these changes

2021-03-08 10:13 UTC, ricardoamaro requested changes
Podes por favor colocar o video no youtube ou algo dedicado a videos?
obrigado

2021-03-08 14:27 UTC, merged